name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build

        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Notify
        run: curl -d "Bridget is up!!" ${{ secrets.NTFY }}

      - name: Cleanup Unused Images
        run: docker image prune -f



