name: Docker Runner

on:
  push:
    branches: [ dev ]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build

        env:
          TOKENDEV: ${{ secrets.TOKENDEV }}

      - name: Cleanup Unused Images
        run: docker image prune -f



